name: Online-edit change updating build
on:
  workflow_dispatch:
  push:
    branches:
      - online-edit
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-node@v3
      with:
        node-version: 16
    - run: npm install -g canopy-js
    - name: Build and deploy JSON changes
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        canopy bulk --finish

        TOPICS_CHANGES=$(git status --porcelain | grep "topics/")
        if [[ ! -z $TOPICS_CHANGES ]]; then
          canopy build
          cd build
          git init
          git config user.name "Cheshbonos User"
          git config user.email "105236136+cheshbonos@users.noreply.github.com"
          git remote add origin "https://cheshbonos:${GITHUB_TOKEN}@github.com/cheshbonos/cheshbonos.git"
          git fetch origin
          build_branch_exists="$(git ls-remote --heads origin build)"
          if [[ ! -z $build_branch_exists ]]; then
            git reset origin/build
          fi
          cp ../.github/workflows/netlify.toml .
          git add -A .
          git status
          git commit -m "Rebuild JSON at ${rev}" --allow-empty
          git push -q origin HEAD:build
        fi
